import json
from datetime import datetime, timezone
from typing import List, Optional
from sqlalchemy import Column, Integer, String, Text, DateTime, ForeignKey
from sqlalchemy.orm import relationship
from app.database import Base


def utcnow():
    return datetime.now(timezone.utc)


class Paper(Base):
    """Represents a research paper stored in the local persistent library."""
    __tablename__ = "papers"

    id = Column(Integer, primary_key=True, index=True, autoincrement=True)
    title = Column(String(512), nullable=False, index=True)
    authors_json = Column(Text, nullable=True)  # JSON string array of authors
    publication_year = Column(Integer, nullable=True, index=True)
    abstract = Column(Text, nullable=True)
    url = Column(String(1024), nullable=True)
    doi = Column(String(256), unique=True, nullable=True, index=True)
    arxiv_id = Column(String(128), unique=True, nullable=True, index=True)
    source = Column(String(64), nullable=False, default="search")  # "openalex", "arxiv", "upload"
    pdf_file_path = Column(String(1024), nullable=True)
    full_text = Column(Text, nullable=True)
    created_at = Column(DateTime, default=utcnow)
    updated_at = Column(DateTime, default=utcnow, onupdate=utcnow)

    # Relationships with automatic cascade deletion
    summary = relationship("Summary", back_populates="paper", uselist=False, cascade="all, delete-orphan")
    qa_messages = relationship("QAMessage", back_populates="paper", cascade="all, delete-orphan", order_by="QAMessage.created_at")

    @property
    def authors(self) -> List[str]:
        """Convenience property to decode authors from JSON string."""
        if not self.authors_json:
            return []
        try:
            return json.loads(self.authors_json)
        except Exception:
            return [self.authors_json]

    @authors.setter
    def authors(self, value: List[str]):
        """Convenience setter to encode authors list into JSON string."""
        self.authors_json = json.dumps(value or [])

    @property
    def has_pdf(self) -> bool:
        """Indicates if a local PDF file is associated with this paper."""
        return bool(self.pdf_file_path and len(self.pdf_file_path.strip()) > 0)

    @property
    def pdf_url(self) -> Optional[str]:
        """Safe relative backend API endpoint to view/stream the PDF without leaking filesystem paths."""
        if self.has_pdf and self.id:
            return f"/api/pdf/{self.id}/view"
        return None

    @property
    def has_summary(self) -> bool:
        """Indicates if an LLM summary has been generated for this paper."""
        return bool(self.summary is not None)


class Summary(Base):
    """Cached structured summary generated by an LLM for a specific paper."""
    __tablename__ = "summaries"

    id = Column(Integer, primary_key=True, index=True, autoincrement=True)
    paper_id = Column(Integer, ForeignKey("papers.id", ondelete="CASCADE"), nullable=False, unique=True, index=True)
    summary_text = Column(Text, nullable=False)
    key_points_json = Column(Text, nullable=True)  # JSON string list of bullet points
    model_used = Column(String(128), nullable=True)
    created_at = Column(DateTime, default=utcnow)
    updated_at = Column(DateTime, default=utcnow, onupdate=utcnow)

    paper = relationship("Paper", back_populates="summary")

    @property
    def key_points(self) -> List[str]:
        if not self.key_points_json:
            return []
        try:
            return json.loads(self.key_points_json)
        except Exception:
            return []

    @key_points.setter
    def key_points(self, value: List[str]):
        self.key_points_json = json.dumps(value or [])


class QAMessage(Base):
    """A user or assistant message in an interactive Q&A session for a paper."""
    __tablename__ = "qa_messages"

    id = Column(Integer, primary_key=True, index=True, autoincrement=True)
    paper_id = Column(Integer, ForeignKey("papers.id", ondelete="CASCADE"), nullable=False, index=True)
    role = Column(String(32), nullable=False)  # "user" or "assistant"
    message = Column(Text, nullable=False)
    context_used = Column(Text, nullable=True)
    created_at = Column(DateTime, default=utcnow)

    paper = relationship("Paper", back_populates="qa_messages")
